version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '8888:80'
      - '443:443'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/keys:/etc/nginx/certs:ro
    # networks:
    #   default:
    #     aliases:
    #       - console-medilink.com
    depends_on:
      - php
      - postgres
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    # ports:
    #     -'3000:9000'
  postgres:
    build:
      context: .
      dockerfile: dockerfiles/postgres.dockerfile
    env_file:
      - ./env/postgres.env
    ports:
      - '5432:5432'
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  cake:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ['php', '/var/www/html/bin/cake.php']

  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ['npm']
    volumes:
      - ./src:/var/www/html
