version: '3.8'
services:
  nginx:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /var/www/html/vendor
    depends_on:
      - php
      - postgres
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./app:/var/www/html:delegated
      - /var/www/html/vendor
  postgres:
    build:
      context: .
      dockerfile: dockerfiles/postgres.dockerfile
    volumes:
      - data5:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  pgadmin:
    image: dpage/pgadmin4:4.2
    ports:
      - 8888:80
    volumes:
      - pgadmin4:/var/lib/pdadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: password
    # depends_on:
    #   - postgres
    # restart: always
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./app:/var/www/html
  cake:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - /var/www/html/vendor
      - ./app:/var/www/html
    entrypoint: [ 'php', '/var/www/html/bin/cake.php' ]
  phinx:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - /var/www/html/vendor
      - ./app:/var/www/html
    entrypoint: ['php', '/var/www/html/vendor/bin/phinx']
volumes:
  data5:
  pgadmin4:
